name		'juniorsysadmin-adoberepo'
version		'0.0.2' 
source		'git://github.com/juniorsysadmin/puppet-adoberepo.git'
author		'Ben Spiccia'
summary		'Module for installing the Adobe YUM repository'
description 	'This module installs the Adobe YUM repository which hosts up to date versions of the Adobe Flash plugin'
license     	'Apache License, Version 2.0'
project_page 'https://github.com/juniorsysadmin/puppet-adoberepo'

dependency  'treydock/gpg_key', '>= 0.0.3'
project_page 'https://github.com/juniorsysadmin/puppet-adoberepo'
